### ISSUE TITLE
AAC Specific Training Exercises

### ISSUE THREAD

**Issue by jasonjoyce971** [jasonjoyce971/GOL_Training_Ground_17#21]
- [x] Raven HLS Generator #26 
- [x] Raven Urban HLS Generator #26 
- [x] Raven Special Insert Course #26 
- [x] Raven Air Assault Target Generator #26 
- [x] Giant HLS Generator #26 
- [x] Giant Sling Load DZ Generator? -> Depending on current sling bugs #26 
- [x] Condor VTOL HLS Generator #26 
- [x] Condor DZ Generator #26 
- [x] Range Generator: #25 
- [x] Banshee ACM Training #26 
- [x] Anvil Training Area #27 
- [x] Emergency Procedure Training #26 
- [x] Mortar Course

**Comment by jasonjoyce971** [comment]
Initial Server Test:
- [x] Choppers not spawned
- [x] Solo Flight throws script error about GVAR soloBird. Caused by above
