### ISSUE TITLE
AAC Ranges Checklist

### ISSUE THREAD

**Issue by jasonjoyce971** [jasonjoyce971/GOL_Training_Ground_17#25]
Aircraft:  
- [x] Rocket/Gunnery Range #26 
- [x] ATGM Range #26 
- [x] Bomb Range  #26 
- [x] ARM Range #26 

Ground Units:
- [x] Dragon Mortar Range
- [x] Anvil Vehicle Range #27 
- [x] Hunter Long Distance Range

**Comment by jasonjoyce971** [comment]
LRR Range functional but scoreboard does not show data.

Cosmetic fault that will probably require a complete re-write of the BIS code used as a template
